### ISSUE TITLE
main.ndx文件的結構

### ISSUE THREAD

**Issue by jack6th** [heavenchou/CBReader#1]
由於在CBReader v056的源碼中沒有找到Monster部分的源碼（好像和此github上的Monster也不太一樣），
能否解釋一下bookcase_v055_20200827.zip中index/main.ndx文件的結構。

**Comment by heavenchou** [comment]
github上的Monster是 2016 年之前的版本，而且是修改成可在 linux 上使用的，所以不太相同，但結構資料結構是相同的，程式也是大同小異。

2018 的版本，也就是目前的版本，基於一些原因，全文檢索的部份就沒有公開了。

若您願意，可以寫信到 CBETA 官網 ( service@cbeta.org )，我可以寄一些資料給您，以前也有網友來信討論過，那些資料應該夠清楚。
